---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Three.
--- DateTime: 10.05.2018 10:40
---
module("logic")

local environment = {}

function setEnvironment(newEnvironment)
    environment = newEnvironment
end

function onNewJobAdded(networks)

end

function onSimulationFinished()
    environment.onNewSimulation()
end

function simulateFrame()

    environment.onNewFrame()

    local state = environment.getEvaluationState()

    if state.isFinished then
        onSimulationFinished()
    else
        local network = {} -- TODO: actual network
        local inputs = environment.getInputs()

        network:setInputs(inputs)
        evaluateNetwork(network)
        local outputs = network:getOutputs()

        environment.mapOutputs(outputs)

        emu.frameadvance()
    end

end