---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Three.
--- DateTime: 10.05.2018 22:54
---

local client = require("client")
local logic = require("logic")
local mario = require("environment_mario1")

local netClientHandlers = {
    onNewNetworksAdded = logic.addNetworks;
    onFrameSimulation = logic.simulateFrame;
}

logic.event.onNetworkEvaluated = client.sendEvaluationResult

logic.setEnvironment(mario)
client.setCallbackHandlers(netClientHandlers)

client.startNetworkConnectionLoop("localhost", 34710)
