---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Three.
--- DateTime: 10.05.2018 22:54
---

local client = require("client")
local logic = require("logic")
local mario = require("environment_mario1")

logic.setEnvironment(mario)

local logicHandlers = {
    -- TODO: link logic to client
}

local netClientHandlers = {
    -- TODO: link client to logic
}

logic.setCallbackHandlers(logicHandlers)
client.setCallbackHandlers(netClientHandlers)

client.startNetworkConnectionLoop("localhost", 34710)
